# Generated by Django 3.1.1 on 2020-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
